// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ddztvsiwpvxewwjmpixz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRkenR2c2l3cHZ4ZXd3am1waXh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1MjIxMTYsImV4cCI6MjA2MTA5ODExNn0.f5oW2TtntTLSZbXrMtu8Vv4LAoCYDo86s9ky132kVG0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);